apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-demo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: project-demo 
  source:
    repoURL: https://dev.azure.com/prasadnaidu10820520/Prasad-Pruefung/_git/jll-challenge
    path: charts/app-demo/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true