apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-demo
  name: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-demo
    spec:
      containers:
      - image: nginx:1.25
        name: nginx
        resources: {}
status: {}